[package]
name = "chessground"
version = "0.8.0" # remember to update html_root_url
description = "A chessboard widget for Relm/GTK"
repository = "https://github.com/niklasf/rust-chessground"
readme = "README.md"
license = "GPL-3.0+"
authors = ["Niklas Fiekas <niklas.fiekas@backscattering.de>"]
categories = ["games", "gui"]
keywords = ["chess"]

[dependencies]
gtk = "0.5.0"
gdk = "0.9.0"
cairo-rs = "0.5.0"
rsvg = { git = "https://github.com/niklasf/rsvg-rs.git", branch = "gtk-0.5" }
time = "0.1"
relm = "0.15"
relm-derive = "0.15"
shakmaty = "0.11"

[dev-dependencies]
rand = "0.5"
relm-attributes = "0.15"
